name: Test Agent Setup

on:
    push:
        branches: [main]
        paths:
            - .github/workflows/test-agent-setup.yml
    pull_request:
        paths:
            - .github/workflows/test-agent-setup.yml

permissions:
    contents: read

jobs:
    test-setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  fetch-depth: 0
                  fetch-tags: true
                  persist-credentials: false
                  submodules: recursive
            - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
              with:
                  distribution: temurin
                  java-version: 21
            - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
            - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
              with:
                  python-version: 3.x
            - name: Install pre-commit
              run: pip install pre-commit
            - name: Install pre-commit hooks
              run: pre-commit install --install-hooks
            - name: Fetch Gradle tools
              run: ./gradlew tasks
